 #pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorF,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorG,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorH,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorI,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorJ,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Include file to "handle" the Bluetooth messages.
//#include "drivers/HTMAG-driver.h"

#include "flightL.txt"

//============================================================================
void playback_flight() {

   int   i;
   i = 0;
   ClearTimer(T4);
   while (flight[i][0] >= 0) {
      while (time1[T4] < flight[i][0]) {
         wait1Msec(1);
      }
      motor[motorE] = flight[i][1];
      motor[motorF] = flight[i][2];
      motor[motorJ] = flight[i][3];
      motor[motorI] = flight[i][4];
      motor[motorG] = flight[i][5];
      motor[motorH] = flight[i][6];
		servoTarget[servo1] = flight[i][7];
      i++;
   }
}
void resetEncoders() {
	nMotorEncoderTarget[motorJ] = 0;
	nMotorEncoderTarget[motorI] = 0;
	motor[motorJ] = -10;
	motor[motorI] = 10;
	nMotorEncoder[motorE] = 0;
	nMotorEncoder[motorF] = 0;
	nMotorEncoder[motorG] = 0;
	nMotorEncoder[motorH] = 0;

	while(true) {
		if(nMotorEncoder[motorJ] <= 0) {
			motor[motorJ] = 0;
		}
		if(nMotorEncoder[motorI] >= 0) {
			motor[motorI] = 0;

		}
		wait10Msec(1);
		eraseDisplay();
		nxtDisplayTextLine(6, "I %d", nMotorEncoder[motorI]);
		nxtDisplayTextLine(7, "J %d", nMotorEncoder[motorJ]);
	}


}
//============================================================================
void initializeRobot()
{
	nMotorEncoder[motorJ] = 0;
	nMotorEncoder[motorI] = 0;
	return;
}

task main()
{
	waitForStart();
	initializeRobot();
   playback_flight();
	resetEncoders();
   StopAllTasks();
}
