#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     LSensor,        sensorLightActive)
#pragma config(Sensor, S4,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h"
#include "heading.c"

task main()
{
	startTask(heading);
	while(true)
	{
  	nxtDisplayCenteredTextLine(3, "Gryo %f", currHeading);  // display "Sensor Value: ##"
  	wait1Msec(10);  // Wait 100 milliseconds to help display correctly
	}

/*	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder(motorRight) = 0;
  motor(motorLeft) = 30;
	motor(motorRight) = 30;

	while(SensorValue[IRsensor] != 6)  // infinite loop:
	{
  	nxtDisplayCenteredTextLine(3, "Sensor Value: %d", SensorValue[IRsensor]);  // display "Sensor Value: ##"
  	wait1Msec(10);  // Wait 100 milliseconds to help display correctly
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;
	PlayTone(784, 15);  // play a tone at a frequency of 784 for 150 milliseconds
	wait1Msec(1000);

	//Score Autonomus

	motor(motorLeft) = 30;
	motor(motorRight) = 30;
	while(nMotorEncoder[motorLeft] > 360 * 4 * 10.6 * -1)
	{
		nxtDisplayCenteredTextLine(3, "Encoder: %d", nMotorEncoder[motorLeft]);
		wait1Msec(10);
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;

	//90 Degree Turn
	motor(motorLeft) = 30;
	motor(motorRight) = -30;
	//StartTask(heading);
	while(currHeading < 90)
	{
		nxtDisplayCenteredTextLine(3, "Heading: %d", currHeading);
		wait1Msec(10);
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;
	wait1Msec(30000);

	int lightval = 0;
	lightval = SensorValue[LSensor];
	motor(motorLeft) = 30;
	motor(motorRight) = 30;

	while(SensorValue(LSensor) <= (lightval + 4))
	{
  	nxtDisplayCenteredTextLine(3, "Sensor Value: %d", SensorValue[LSensor]);  // display "Sensor Value: ##"
  	wait1Msec(10);  // Wait 100 milliseconds to help display correctly
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;
	PlayTone(784, 15);  // play a tone at a frequency of 784 for 150 milliseconds
	wait1Msec(1000); */
}
