#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     LSensor,        sensorLightActive)
#pragma config(Sensor, S4,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h"
float currHeading = 0.0;

void FunctionIRstage()
{
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;
	PlayTone(220, 15);
  motor(motorLeft) = 30;
	motor(motorRight) = 30;
	PlayTone(784, 15);
	while(SensorValue[IRsensor] != 6)  // infinite loop:
	{
  	nxtDisplayCenteredTextLine(2, "Sensor Value: %d", SensorValue[IRsensor]);  // display "Sensor Value: ##"
  	wait1Msec(10);  // Wait 100 milliseconds to help display correctly
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;
	PlayTone(784, 15);  // play a tone at a frequency of 784 for 150 milliseconds
}

void FunctionToWall()
{
	//Score Autonomus goes here XD

	motor(motorLeft) = 30;
	motor(motorRight) = 30;
	while(nMotorEncoder[motorRight] > 360 * 4 * 10.6 * -1)
	{
		nxtDisplayCenteredTextLine(4, "Encoder: %d", nMotorEncoder[motorRight]);
		wait1Msec(10);
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;
}

void FunctionTurn()
{
	//90 Degree Turn
	motor(motorLeft) = 30;
	motor(motorRight) = -30;
}

void FunctionToWhiteLine()
{
	//White Line to Ramp
	int lightval = 0;
	lightval = SensorValue[LSensor];
	motor(motorLeft) = 30;
	motor(motorRight) = 30;

	while(SensorValue(LSensor) <= (lightval + 4))
	{
  	nxtDisplayCenteredTextLine(1, "Sensor Value: %d", SensorValue[LSensor]);  // display "Sensor Value: ##"
  	wait1Msec(10);  // Wait 100 milliseconds to help display correctly
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;
	PlayTone(784, 15);  // play a tone at a frequency of 784 for 150 milliseconds
	wait1Msec(1000);
}

void FunctionHeading()
{
	currHeading = 0.0;
	while(currHeading < 85.0 || currHeading > 270.0)
	{
		wait1Msec(20);
	}

	motor(motorLeft) = 0;
	motor(motorRight) = 0;

	wait1Msec(1000);
}


task heading()
{
	float delTime = 0.0;
	float prevHeading = 0.0;
	float curRate = 0.0;
	HTGYROstartCal(GYRO);
   while (true) {
   	time1[T1] = 0;
    	curRate = HTGYROreadRot(GYRO);
    	if (abs(curRate) > 5) {
      	prevHeading = currHeading;
      	currHeading = prevHeading + (curRate * delTime);
      	if (currHeading > 360) currHeading -= 360;
      	else if (currHeading < 0) currHeading += 360;
    		}
    nxtDisplayTextLine(3, "Curr = %f", currHeading);
   	wait1Msec(5);
    	delTime = ((float)time1[T1]) / 1000;
    	//delTime /= 1000;

	}
}

task main()
{
	StartTask(heading, 50);
	FunctionHeading();
	FunctionIRstage();
	FunctionToWall();
	FunctionTurn();
	FunctionToWhiteLine();

}
