#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
task main()
{
	int click = 0;
	while(true)
	{
		getJoystickSettings(joystick);
		motor[motorD] = 100.0 * (joystick.joy1_y1 + joystick.joy1_x1) / (127.0 + (float)abs(joystick.joy1_x1) ) ;
		motor[motorF] = 100.0 * (joystick.joy1_y1 - joystick.joy1_x1) / (127.0 + (float)abs(joystick.joy1_x1) ) ;
		if(joy1Btn(1) ==1 && click == 1)
		{
			motor[motorH] = 0;
			click = 0;
		}else if(joy1Btn(1) == 1 && click == 0)
		{
			motor[motorH] = 100;
			click = 1;
		}
	}
}
