#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Flagspinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Spinmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ShoulderMotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ElbowMotor,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "AutoLibraryDeux.c"

task main()
{
			nVolume = 1;
			playTone(440, 500);
			//Drive Forward
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			wait10Msec(75);
  		motor[MOTOR_LEFT] = 25;
			motor[MOTOR_RIGHT] = 25;
    	driveTo(24);
    	motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			// Turn Around
			playTone(440, 500);
			gyroTurn(20, 90);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			gyroTurn(20, 90);
			//Drive Back
			playTone(440, 500);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			wait10Msec(75);
			motor[MOTOR_LEFT] = 25;
			motor[MOTOR_RIGHT] = 25;
    	driveTo(48);
    	motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			//Test Arm

			//Test Spinner
			playTone(440, 500);
			motor[Spinmotor] = 100;
			wait1Msec(1000);
			motor[Spinmotor] = 0;
			//Test Flag
			playTone(440, 500);
			motor[Flagspinner] = 100;
			wait1Msec(1000);
			motor[Flagspinner] = 0;
			//Test Servo
			playTone(440, 500);
			servoTarget(servo6) = 180;
			wait1Msec(500);
			servoTarget(servo6) = 0;
			wait1Msec(500);


}
