#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Flagspinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Spinmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ShoulderMotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ElbowMotor,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "AutoLibraryDeux.c"

task main()
{
	wait1Msec(3);
	int ending = interface();
	wait1Msec(1000);
	int timing = timeinterface();
	servo(servo6) = 0;
	waitForStart();


	wait10Msec(timing * 100);
	initialize();
	wait10Msec(30);

	// Move away from the wall
	motor[MOTOR_LEFT] = -40;
	motor[MOTOR_RIGHT] = -40;
	driveTo(4);
	motor[MOTOR_LEFT] = 0;
	motor[MOTOR_RIGHT] = 0;


	// Turn toward the west wall
	gyroTurn(20, 87);
	motor[MOTOR_LEFT] = 0;
	motor[MOTOR_RIGHT] = 0;
	nMotorEncoder[MOTOR_LEFT] = 0;
	nMotorEncoder[MOTOR_RIGHT] = 0;

	// Drive toward the west wall
	motor[MOTOR_LEFT] = -40;
	motor[MOTOR_RIGHT] = -40;
	driveTo(25);
	motor[MOTOR_LEFT] = 0;
	motor[MOTOR_RIGHT] = 0;


	// Turn toward the baskets
	gyroTurn(-20, 42);
	nMotorEncoder[MOTOR_LEFT] = 0;
	nMotorEncoder[MOTOR_RIGHT] = 0;
	//-------------------------------

	// We're aligned with the baskets.
	// Start walking along them looking for the IR beacon
	motor[MOTOR_LEFT] = -40;
	motor[MOTOR_RIGHT] = -40;
 	driveTo(4);
	if(CheckIR(4) || checkIR(5)) // The first basket
	{
		motor[MOTOR_LEFT] = 0;
		motor[MOTOR_RIGHT] = 0;
		wait10Msec(4);
		servoTarget(servo6) = 180;
		wait10Msec(50);
		//forward/back
	}else { // The second basket
		driveTo(13);
		if(checkIR(4) || checkIR(5))
		{
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			servoTarget(servo6) = 180;
			wait10Msec(150);
			//forward/back
		}else{ // The third basket
			driveTo(35);
			if(sensorValue[IRsensor] == 6 || sensorValue[IRsensor] == 5)
			{
				motor[MOTOR_LEFT] = 0;
				motor[MOTOR_RIGHT] = 0;
				servoTarget(servo6) = 180;
				wait10Msec(150);
				//place block
				//forward/back
			}else{ // The fourth basket
				driveTo(45);
				motor[MOTOR_LEFT] = 0;
				motor[MOTOR_RIGHT] = 0;
				servoTarget(servo6) = 180; // Deploy the auto-scoring arm
				wait10Msec(150);
				//forward/back

			}
		}
	}
	servoTarget[servo6] = 0; // Retract the auto-scoring arm
	switch(ending)   // test 'nTaskToStart' in the switch
	{
  	case 1:											// if 'nTaskToStart' is '1':
  		// Drive to the end of the baskets.
			motor[MOTOR_LEFT] = 50;
			motor[MOTOR_RIGHT] = 50;
			while(abs(nMotorEncoder[MOTOR_RIGHT]) > 100)
			{
			}
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;

			// Turn toward the ramp
			gyroTurn(20, 50);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;

			// Drive in front of the ramp
			motor[MOTOR_LEFT] = 90;
			motor[MOTOR_RIGHT] = 90;
			driveTo(20);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;

			// Turn toward the ramp agai
			gyroTurn(20, 50);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;

			motor[MOTOR_LEFT] = 90;
			motor[MOTOR_RIGHT] = 90;
			driveTo(30);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			gyroTurn(20, 60);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = 50;
			motor[MOTOR_RIGHT] = 50;
			driveTo(40);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
    	break;                 // break out of this switch statement and continue code after the '}'

  	case 2:                // if 'nTaskToStart' is '2':
			motor[MOTOR_LEFT] = -90;
			motor[MOTOR_RIGHT] = -90;
    	driveTo(51);
    	motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;



			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = -90;
			motor[MOTOR_RIGHT] = -90;
			driveTo(10);
    	motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			gyroTurn(-40, 70);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = -50;
			motor[MOTOR_RIGHT] = -50;
			driveTo(35);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			gyroTurn(-40, 90);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = -90;
			motor[MOTOR_RIGHT] = -90;
			driveTo(35);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
		/*	gyroTurn(-20, 70);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = 90;
			motor[MOTOR_RIGHT] = 90;
			driveTo(40);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0; */
			// start task Two
    	break;                 // break out of this switch statement and continue code after the '}'

  	default:               // if 'nTaskToStart' is anything other than '1' or '2':
    	      // start task Three
	}


}
