#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Flagspinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Spinmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ShoulderMotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ElbowMotor,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "AutoLibrary.c"

void initializeRobot()
{
	servo[servo6] = 0;
	bFloatDuringInactiveMotorPWM = false;
	wait1Msec(3);
  return;
}

task main()
{
//Starting block; Pull forward, turn.
  initializeRobot();
	waitForStart();
	StartTask(heading, 50);
	nMotorEncoder[LeftDrive] = 0;
	nMotorEncoder[RightDrive] = 0;
	driveDistance(30, 1000);
	nMotorEncoder[LeftDrive] = 0;
	nMotorEncoder[RightDrive] = 0;
	int motorSpeed = 20;
	bool scored = false;
//Begin looking for IR

	while(nMotorEncoder[RightDrive] < 6000 && scored == false)
	{
		nxtDisplayTextLine(2,"encod. %d", nMotorEncoder[RightDrive]);
		if(motorSpeed < 100)
		{
			motor[RightDrive] = motorSpeed;
			motor[LeftDrive] = motorSpeed;
			motorSpeed = motorSpeed + 3;
			wait10Msec(5);
		}
		if(nMotorEncoder[RightDrive] < 1000)
		{
			if(CheckIR(6))
			{
				wait1Msec(200);
				motor[LeftDrive] = 0;
				motor[RightDrive] = 0;
				servoTarget(servo6) = 230;
				wait10Msec(50);
				scored = true;
			}
		}
		//-------------
		if(nMotorEncoder[RightDrive] < 2750 && nMotorEncoder[RightDrive] > 1000)
		{
			if(CheckIR(5))
			{
				motor[LeftDrive] = 0;
				motor[RightDrive] = 0;
				servoTarget(servo6) = 230;
				wait10Msec(50);
				scored = true;
			}
		}
		//----------------
		if(nMotorEncoder[RightDrive] < 4500 && nMotorEncoder[RightDrive] > 2750)
		{
			if(CheckIR(5))
			{
				motor[LeftDrive] = 0;
				motor[RightDrive] = 0;
				servoTarget(servo6) = 230;
				wait10Msec(100);
				scored = true;
			}
		}
		//--------------
		if(nMotorEncoder[RightDrive] < 6000 && nMotorEncoder[RightDrive] > 4500)
		{
			if(CheckIR(4))
			{
				motor[LeftDrive] = 0;
				motor[RightDrive] = 0;
				servoTarget(servo6) = 230;
				wait10Msec(100);
				scored = true;
			}
		}

	}
	servoTarget(servo6) = 30;
	while(nMotorEncoder[RightDrive] > 750)
	{
		motor[LeftDrive] = -100;
		motor[RightDrive] = -100;
	}
	motor[LeftDrive] = 0;
	motor[RightDrive] = 0;
	gyroTurn(70, 100);
	driveDistance(100, 4000);
	gyroTurn(-70, 90);
	driveDistance(75, 6000);
	PlayTone(500, 500);
	wait10Msec(1000);

}
