#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Flagspinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Spinmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ShoulderMotor, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ElbowMotor,    tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*===================================================================================================================*/
/* hardware and software initialization                                                                              */
#include "JoystickDriver.c"

/*===================================================================================================================*/

/*===================================================================================================================*/
void initializeRobot() {

  // bFloatDuringInactiveMotorPWM = true;
   //nMaxRegulatedSpeed12V = 500;              /* improves motor control */
   bNxtLCDStatusDisplay = true;
   disableDiagnosticsDisplay();
   eraseDisplay();
   //ClearTimer(T1);
   nMotorEncoder[ShoulderMotor] = 0;
   nMotorEncoder[ElbowMotor] = 0;
   motor[ShoulderMotor] = 0;
   motor[ElbowMotor] = 0;
}
/*===================================================================================================================*/
task main() {
tMotor whichMotor = ShoulderMotor;
initializeRobot();
nNxtExitClicks = 3;
   while(true) {
      if(nNxtButtonPressed == 3) {
         if(whichMotor == ShoulderMotor) {
            whichMotor = ElbowMotor;
            wait1Msec(300);
         } else {
            whichMotor = ShoulderMotor;
            wait1Msec(300);
         }
      }
      if(nNxtButtonPressed == 1) {
         motor[whichMotor] = 10;
      } else if(nNxtButtonPressed == 2) {
         motor[whichMotor] = -10;
      }else {
         motor[ShoulderMotor] = 0;
         motor[ElbowMotor] = 0;
      }
      wait1Msec(20);
    if(whichMotor == ShoulderMotor)
   	{
     	nxtDisplayCenteredTextLine(3, "%d", 111);
     	nxtDisplayCenteredTextLine(4, "%d", nMotorEncoder(whichMotor));
   	}else if(whichMotor == ElbowMotor)
   	{
     	nxtDisplayCenteredTextLine(3, "%d", 222);
     	nxtDisplayCenteredTextLine(4, "%d", nMotorEncoder(whichMotor));
   	}
  }
}
/*===================================================================================================================*/
