#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     flagspinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     spinmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ShoulderMotor, tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     ElbowMotor,    tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Tele-op program
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "teleopFunctions.c"

void initializeRobot()
{
  return;
}
task main()
{
	initializeRobot();
  waitForStart();   // wait for start of tele-op phase
  while (true)
  {
  	getJoystickSettings(joystick);
  	updateBase(joystick.joy1_y1, joystick.joy1_x2, RightDrive, LeftDrive);
		updateMotor(joystick.joy2_y1, shoulderMotor);
		updateMotor(joystick.joy2_y2, elbowMotor);
		toggleMotor(joy1Btn(5), spinMotor);

	}
}
