#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
task main()
{
	int click = 0;
	while(true)
	{
		getJoystickSettings(joystick);
		motor[motorD] = joystick.joy1_y1 / 127.0 ;
		motor[motorE] = joystick.joy1_y1 / 127.0 ;
		if(joy1Btn(1) ==1 && click == 1)
		{
			motor[motorF] = 0;
		}else if(joy1Btn(1) == 1 && click == 0)
		{
			motor[motorF] = 100;
		}
	}
}
