#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Flagspinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Spinmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ShoulderMotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ElbowMotor,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo3,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "AutoLibraryDeux.c"

task main()
{
	wait1Msec(3);
	int beginning = beginInterface();
	wait1Msec(500);
	int ending =  interface();
	wait1Msec(1000);
	int timing = timeinterface();
	servo(servo3) = 0;
	waitForStart();


	wait10Msec(timing * 100);
	initialize();
	wait10Msec(30);
	switch(beginning)   // test 'nTaskToStart' in the switch
	{
  	case 1: //Corner


  	case 2: //Wall
		  // Move away from the wall
			motor[MOTOR_LEFT] = 40;
			motor[MOTOR_RIGHT] = 40;
			driveTo(4);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			// Turn toward the west wall
			gyroTurn(-20, 87);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			// Drive toward the west wall
			motor[MOTOR_LEFT] = 40;
			motor[MOTOR_RIGHT] = 40;
			driveTo(28);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			// Turn toward the baskets
			gyroTurn(20, 43);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;

  	case 3: //Fast
  		// Move away from the wall
			motor[MOTOR_LEFT] = 40;
			motor[MOTOR_RIGHT] = 40;
			driveTo(2);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
  /*	case 4: //Masquerad
  	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  		// Move away from the wall
			motor[MOTOR_LEFT] = 40;
			motor[MOTOR_RIGHT] = 40;
			driveTo(2);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;

			accelerate();
		  driveTo(12);
			if(CheckIR(6)) // The first basket
			{
				motor[MOTOR_LEFT] = 0;
				motor[MOTOR_RIGHT] = 0;
				wait10Msec(4);
				servoTarget(servo3) = 180;
				wait10Msec(50);
				//forward/back
			}else { // The second basket
				driveTo(23);
				if(checkIR(5))
				{
					motor[MOTOR_LEFT] = 0;
					motor[MOTOR_RIGHT] = 0;
					servoTarget(servo3) = 180;
					wait10Msec(150);
					//forward/back
				}else{ // The third basket
					driveTo(43);
					if(sensorValue[IRsensor] == 4 || sensorValue[IRsensor] == 5)
					{
						motor[MOTOR_LEFT] = 0;
						motor[MOTOR_RIGHT] = 0;
						servoTarget(servo3) = 180;
						wait10Msec(150);
						//place block
						//forward/back
					}else{ // The fourth basket
						driveTo(52);
						motor[MOTOR_LEFT] = 0;
						motor[MOTOR_RIGHT] = 0;
						servoTarget(servo3) = 180; // Deploy the auto-scoring arm
						wait10Msec(150);
					}
				}
			}
			servoTarget[servo3] = 0;
			gyroTurn(30, 87);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			///
			motor[MOTOR_LEFT] = -40;
			motor[MOTOR_RIGHT] = -40;
			driveTo(10);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			///
			gyroTurn(30, 87);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			///
			motor[MOTOR_LEFT] = 40;
			motor[MOTOR_RIGHT] = 40;
			driveTo(6);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			///
			gyroTurn(-30, 87);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			///
			nMotorEncoder[ShoulderMotor] = 0;
			while(nMotorEncoder[ShoulderMotor] > -3500)
			{
				motor[ShoulderMotor] = -50;
			}

			motor[ShoulderMotor] = 0;
			///
			motor[MOTOR_LEFT] = 40;
			motor[MOTOR_RIGHT] = 40;
			driveTo(10);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			//
			nMotorEncoder[ElbowMotor] = 0;
			while(nMotorEncoder[ElbowMotor] < 3500)
			{
				motor[ElbowMotor] = -10;
			}
			motor[ElbowMotor] = 0;
			///
			motor[Spinmotor] = -100;
			wait10Msec(100);
			motor[Spinmotor] = 0;

			//SPIN SPINNER SPINNILY

			///
			while(nMotorEncoder[ElbowMotor] > 100)
			{
				motor[ElbowMotor] = 10;
			}
			motor[ElbowMotor] = 0;
			///
			while(sensorValue(S2) == 0)
			{
				motor[ShoulderMotor] = 50;
			}
			motor[ShoulderMotor] = 0;
			gyroTurn(30, 87);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
		*/	///
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  	default:
  	//IF YOU MANAGE TO DO THIS YOU ARE A GAWD

  }


	//-------------------------------

	// We're aligned with the baskets.
	// Start walking along them looking for the IR beacon
	accelerate();
  driveTo(12);
	if(CheckIR(6)) // The first basket
	{
		motor[MOTOR_LEFT] = 0;
		motor[MOTOR_RIGHT] = 0;
		wait10Msec(4);
		servoTarget(servo3) = 180;
		wait10Msec(50);
		//forward/back
	}else { // The second basket
		driveTo(23);
		if(checkIR(5))
		{
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			servoTarget(servo3) = 180;
			wait10Msec(150);
			//forward/back
		}else{ // The third basket
			driveTo(43);
			if(sensorValue[IRsensor] == 4 || sensorValue[IRsensor] == 5)
			{
				motor[MOTOR_LEFT] = 0;
				motor[MOTOR_RIGHT] = 0;
				servoTarget(servo3) = 180;
				wait10Msec(150);
				//place block
				//forward/back
			}else{ // The fourth basket
				driveTo(52);
				motor[MOTOR_LEFT] = 0;
				motor[MOTOR_RIGHT] = 0;
				servoTarget(servo3) = 180; // Deploy the auto-scoring arm
				wait10Msec(150);
				//forward/back

			}
		}
	}
	servoTarget[servo3] = 0; // Retract the auto-scoring arm
	switch(ending)   // test 'nTaskToStart' in the switch
	{
  	case 1:											// if 'nTaskToStart' is '1':
  		// Drive to the end of the baskets.
  		motor[MOTOR_LEFT] = 90;
			motor[MOTOR_RIGHT] = 90;
    	driveTo(58);
    	motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;

			// Turn toward the ramp
			gyroTurn(20, 50);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;

			// Drive in front of the ramp
			motor[MOTOR_LEFT] = 90;
			motor[MOTOR_RIGHT] = 90;
			driveTo(18);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;

			// Turn toward the ramp agai
			gyroTurn(20, 50);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;

			motor[MOTOR_LEFT] = 90;
			motor[MOTOR_RIGHT] = 90;
			driveTo(28);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			gyroTurn(-20, 100);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = -100;
			motor[MOTOR_RIGHT] = -100;
			driveTo(40);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
    	break;                 // break out of this switch statement and continue code after the '}'

  	case 2:                // if 'nTaskToStart' is '2':
			motor[MOTOR_LEFT] = -50;
			motor[MOTOR_RIGHT] = -50;
			while(abs(nMotorEncoder[MOTOR_RIGHT]) > 1500)
			{
			}
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;

			//gyroTurn(60, 160);

			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = -90;
			motor[MOTOR_RIGHT] = -90;
			driveTo(5);
    	motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			gyroTurn(-40, 70);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = -50;
			motor[MOTOR_RIGHT] = -50;
			driveTo(30);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
			gyroTurn(-40, 90);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = -90;
			motor[MOTOR_RIGHT] = -90;
			driveTo(35);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0;
		/*	gyroTurn(-20, 70);
			nMotorEncoder[MOTOR_LEFT] = 0;
			nMotorEncoder[MOTOR_RIGHT] = 0;
			motor[MOTOR_LEFT] = 90;
			motor[MOTOR_RIGHT] = 90;
			driveTo(40);
			motor[MOTOR_LEFT] = 0;
			motor[MOTOR_RIGHT] = 0; */
			// start task Two
    	break;                 // break out of this switch statement and continue code after the '}'

  	default:               // if 'nTaskToStart' is anything other than '1' or '2':
    	      // start task Three
	}


}
